window.SITE_CONFIG = {
  clubName: "大業 AI 繪圖社",
  voting: {
    enabled: true,
    apiUrl: "https://script.google.com/macros/s/AKfycbxgCO77XBbXkPfdkc-boGKkES2MmPfifbcn5Dmo_7ByQKHcp5z9a9I6jeGjhv8VzBnVmQ/exec",
    formUrl: "https://docs.google.com/forms/d/1xn0abYP7l1_DxAGoxYy5XkQJIz76re5bx3HxVsu-CIc/viewform",
    gameParamName: "",
    startDate: "2026-06-15",
    endDate: "2026-06-19",
    deadline: "6/19（五）",
    prizeSummary: "待公告",
    prototypeVotingEnabled: false,
  },
  results: {
    csvUrl: "https://docs.google.com/spreadsheets/d/1r61IuxeCxEE8VNvw_ArUzbsmusc2Vhf4_evi6NGZs_E/gviz/tq?tqx=out:csv&gid=731019646",
    refreshSeconds: 60,
    publicRankingsOpen: false,
    useMockVotes: false,
    columns: {
      projectId: "您試玩的作品代號",
      likedMost: "您覺得這款遊戲最吸引人的地方是什麼？",
      suggestion: "若有機會改善，您建議開發者調整哪個部分？",
      creativity: "遊戲體驗評分 [AI 結合創意]",
      art: "遊戲體驗評分 [畫面精緻度]",
      gameplay: "遊戲體驗評分 [遊戲趣味性]",
      smoothness: "遊戲體驗評分 [操作流暢度]",
      completeness: "遊戲體驗評分 [整體體驗滿意度]",
      createdAt: "時間戳記",
    },
  },
};
