const WORKS = [
  {
    code: "701-04",
    title: "701-04 原創遊戲",
    genre: "反應挑戰",
    tagline: "進入節奏快速的挑戰場，測試你的反應與判斷。",
    description: "適合短時間反覆挑戰，看看誰能撐到最後。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "701",
    coverTone: "tone-forest",
    launchUrl: "./games/701-04/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1GtdA0gv97xpMtO9xmhHGYLMlz3SPjUHI"
  },
  {
    code: "701-016",
    title: "701-016 原創遊戲",
    genre: "互動挑戰",
    tagline: "用直覺操作闖過學生設計的遊戲關卡。",
    description: "簡單開始，越玩越想挑戰更高分。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "701",
    coverTone: "tone-sky",
    launchUrl: "./games/701-016/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1vqtBQRozg91MpwgkZ4aj2WnN5Ol1aycL"
  },
  {
    code: "704-08",
    title: "704-08 原創遊戲",
    genre: "創意遊戲",
    tagline: "打開作品，探索作者放進遊戲裡的小巧思。",
    description: "一款由學生完成的 Gemini Canvas 互動作品。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "704",
    coverTone: "tone-amber",
    launchUrl: "./games/704-08/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1CB5omA_LQUpTDBa3QPmLro0uYT099Fqa"
  },
  {
    code: "801-01",
    title: "嘉義美食大亨",
    genre: "模擬經營",
    tagline: "經營在地美食，打造自己的嘉義小吃王國。",
    description: "抽卡、升級、賺錢，讓嘉義名店成為你的餐飲帝國。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "FOOD",
    coverTone: "tone-crimson",
    launchUrl: "./games/801-01/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1D6cMHIXr1_1ELYBne2qaw-WuC8VatObM"
  },
  {
    code: "804-02",
    title: "深海設施射擊戰",
    genre: "3D 射擊",
    tagline: "在黑暗設施中移動、瞄準，面對逼近的敵人。",
    description: "點擊畫面進入沉浸模式，使用 WASD 與滑鼠挑戰生存。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "804",
    coverTone: "tone-indigo",
    launchUrl: "./games/804-02/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1CqeJvX-p3Fe1GMRS2Np2-4kJcfwVAqja"
  },
  {
    code: "804-11",
    title: "音效決鬥",
    genre: "動作音效",
    tagline: "用強烈音效堆出戰鬥感，讓每次觸發都有存在感。",
    description: "打開聲音，體驗節奏與招式音效交織的互動作品。",
    status: "package",
    statusLabel: "上架中",
    shelfLabel: "SOUND",
    coverLetters: "SFX",
    coverTone: "tone-violet",
    launchUrl: "./games/804-11/index.html",
    folderUrl: "https://drive.google.com/drive/folders/19sTKhQ66AGtaZ522NtEBBO3cIAQtQsdf"
  },
  {
    code: "804-14",
    title: "804-14 原創遊戲",
    genre: "創意遊戲",
    tagline: "進入學生設計的互動世界，找出玩法與目標。",
    description: "一款由學生完成的 Gemini Canvas 互動作品。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "804",
    coverTone: "tone-cyan",
    launchUrl: "./games/804-14/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1jIVBoe3B1wJLXqrfuNmi0IXxfTByVMWt"
  },
  {
    code: "904-07",
    title: "904-07 原創遊戲",
    genre: "開發中",
    tagline: "仍在開發中的學生作品，先開放試玩。",
    description: "作品內容可能還會調整，適合以體驗版方式展示。",
    status: "incomplete",
    statusLabel: "開發中",
    shelfLabel: "BETA",
    coverLetters: "904",
    coverTone: "tone-rose",
    launchUrl: "./games/904-07/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1EWG40UHFxxzzUZqsVdPTC1MdNVdqJYJP"
  },
  {
    code: "SDG",
    title: "永續島嶼建設者",
    genre: "建設模擬",
    tagline: "在發展、環境與社會福祉之間做出你的選擇。",
    description: "打造島嶼、處理永續議題，看看你的城市能走多遠。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "SDG",
    coverTone: "tone-lime",
    launchUrl: "./games/sdg/index.html",
    folderUrl: "https://drive.google.com/drive/folders/11X-1QYl7Cscq6rnuwj7DeBpTor9UCUmP"
  }
];
