const EVENT_CONFIG = {
  title: "大業 AI 繪圖社期末成果展",
  subtitle: "遊戲創作 × AI 視覺 × 觀眾票選",
  purpose: "學生自製遊戲正式上線。AI 視覺、遊戲企劃、互動程式，全部變成可以試玩的作品。這一次，人氣王不由老師決定，而是交給觀眾。",
  votingRule: "6/15（一）至 6/19（五）23:59 開放線上票選。先進作品頁試玩，再點「投這件當人氣王」送出你的支持；每個 Google 帳號可填答 1 次，也可以留下給作者的真實建議。",
  participationValue: "你投下的不只是普通一票，而是把喜歡的作品推向人氣獎；你留下的一句建議，也會成為作者調整玩法、畫面、操作與作品介紹的下一步線索。",
  notice: "留言與建議請勿填寫姓名、班級、座號、學號或聯絡方式。",
  startDate: "6/15（一）",
  deadline: "6/19（五）23:59",
};

const PROJECTS = [
  {
    id: "G01",
    title: "歡樂時光屋",
    cover: "./assets/games/happy-house-3d/cover-4x3.png",
    genre: ["3D", "劇情探索"],
    tags: ["3D", "馬戲團", "劇情", "氛圍"],
    platform: "Web",
    shortPitch: "推開歡樂時光屋的帳篷，每個齒輪轉動都是線索。",
    description: "3D 劇情探索類遊戲，玩家在馬戲團與機械世界的混合空間中尋找線索、解開時光屋的秘密。重視氛圍、視覺與探索節奏。",
    playUrl: "./games/701-04/index.html",
    theme: "ember",
    featured: true,
    createdAt: "2026-05-10",
  },
  {
    id: "G02",
    title: "風味抉擇：漢堡帝國",
    cover: "./assets/games/burger-empire/cover-16x9.jpg",
    boxCover: "./assets/games/burger-empire/cover-2x3.jpg",
    genre: ["模擬經營", "策略"],
    tags: ["餐廳", "資源管理", "升級", "決策"],
    platform: "Web",
    shortPitch: "你以為只是賣漢堡？每個決定都在考驗你的老闆腦。",
    description: "價格、人氣、口碑與資金一起壓上來，玩家要在連續選擇中把小店推向漢堡帝國。",
    playUrl: "./games/701-016/index.html",
    theme: "gold",
    featured: true,
    createdAt: "2026-05-12",
  },
  {
    id: "G03",
    title: "八掌溪跑酷",
    cover: "./assets/games/bazhang-parkour/cover-16x9.jpg",
    boxCover: "./assets/games/bazhang-parkour/cover-2x3.jpg",
    genre: ["跑酷", "動作"],
    tags: ["第一人稱", "在地場景", "速度", "反應"],
    platform: "Web",
    shortPitch: "夕照很美，但你沒有時間欣賞。",
    description: "以八掌溪為靈感的第一人稱跑酷挑戰，玩家要在速度、視角與障礙中維持節奏。",
    playUrl: "https://archie108310-stack.github.io/3/",
    theme: "sunset",
    featured: true,
    createdAt: "2026-05-13",
  },
  {
    id: "G04",
    title: "嘉義美食大亨",
    cover: "./assets/games/chiayi-food-tycoon/cover-16x9.jpg",
    boxCover: "./assets/games/chiayi-food-tycoon/cover-2x3.jpg",
    genre: ["模擬經營", "收集"],
    tags: ["嘉義", "美食", "抽卡", "養成"],
    platform: "Web",
    shortPitch: "從一盤小吃開始，吃下整座嘉義的市場。",
    description: "以在地美食包裝收集與升級節奏，讓每一次開店、抽卡與養成都有明確回饋。",
    playUrl: "./games/801-01/index.html",
    theme: "citrus",
    featured: true,
    createdAt: "2026-05-15",
  },
  {
    id: "G05",
    title: "第三次世界大戰",
    cover: "./assets/games/gunfight/cover-16x9.jpg",
    genre: ["射擊", "3D"],
    tags: ["FPS", "HUD", "戰場", "WASD"],
    platform: "Web",
    shortPitch: "彈匣剩 28 發，遠方有東西在動。",
    description: "第一人稱戰場射擊：HUD 顯示彈藥與生命，在廢墟與沼地之間移動、瞄準、開火，撐過下一波壓上來的敵人。",
    playUrl: "./games/804-02/index.html",
    theme: "deep",
    featured: true,
    createdAt: "2026-05-17",
  },
  {
    id: "G06",
    title: "八掌溪環保爭霸戰",
    cover: "./assets/games/bazhang-eco-battle/cover-4x3.png",
    boxCover: "./assets/games/bazhang-eco-battle/cover-2x3.jpg",
    genre: ["環境教育", "策略"],
    tags: ["八掌溪", "永續", "知識", "對戰"],
    platform: "Web",
    shortPitch: "如果八掌溪需要一位守門人，你會怎麼出手？",
    description: "把環境知識轉成策略選擇，讓玩家用行動守住生態，也守住分數。",
    playUrl: "./games/804-14/index.html",
    theme: "river",
    featured: false,
    createdAt: "2026-05-19",
  },
  {
    id: "G07",
    title: "深淵騎士",
    cover: "./assets/games/dark-cell/cover-16x9.jpg",
    boxCover: "./assets/games/dark-cell/cover-2x3.jpg",
    genre: ["平台跳躍", "動作"],
    tags: ["騎士", "關卡", "技能", "挑戰"],
    platform: "Web",
    shortPitch: "往前走，深淵會告訴你哪一步太慢。",
    description: "以平台動作為核心，結合角色技能、敵人封鎖與關卡節奏。",
    playUrl: "./games/904-07/index.html",
    theme: "crimson",
    featured: false,
    createdAt: "2026-05-20",
  },
  {
    id: "G08",
    title: "拯救永續島",
    cover: "./assets/games/sdg/cover-16x9.jpg",
    genre: ["建設模擬", "策略"],
    tags: ["SDG", "城市", "永續", "治理", "五分鐘決策"],
    platform: "Web",
    shortPitch: "一座島，三個指標，五分鐘決策。你救得了它嗎？",
    description: "在《拯救永續島》中，你將扮演島嶼決策者，透過造林、建設、工業發展與 SDG 任務選擇，平衡生態、經濟與社會福祉。每個選擇都有代價，每次建設都會改變島嶼命運。",
    playUrl: "./games/sdg/index.html",
    theme: "forest",
    featured: false,
    createdAt: "2026-05-21",
  },
  {
    id: "G09",
    title: "ECO Defender's Bizarre Adventure",
    cover: "./assets/games/eco-defenders/cover-16x9.jpg",
    genre: ["動作冒險", "環境教育"],
    tags: ["3D", "環保", "探索", "戰鬥"],
    platform: "Web",
    shortPitch: "清理污染、守住自然，讓黃金守護者跟你一起反擊。",
    description: "一款立體環保冒險遊戲，玩家在自然與污染交界的世界中探索、戰鬥與復原環境，用行動完成守護任務。",
    playUrl: "./games/eco-defenders/index.html",
    theme: "leaf",
    featured: true,
    createdAt: "2026-06-04",
  },
  {
    id: "G10",
    title: "微型死域",
    cover: "./assets/games/micro-dead-zone/cover-4x3.jpg",
    genre: ["射擊", "生存"],
    tags: ["工廠", "獵場", "越肩視角", "Three.js", "滑鼠鎖定"],
    platform: "Web",
    shortPitch: "當整座工廠變成獵場，你還能活到天亮嗎？",
    description: "黑暗工廠裡的越肩視角生存射擊遊戲。玩家使用滑鼠瞄準、WASD 移動，在迷霧、手電筒與機械敵人的追擊中尋找活路。",
    playUrl: "./games/micro-dead-zone/index.html",
    theme: "deep",
    featured: false,
    createdAt: "2026-06-11",
  },
  {
    id: "G11",
    title: "霓虹星際突擊",
    cover: "./assets/games/neon-star-assault/cover-16x9.jpg",
    genre: ["射擊", "動作"],
    tags: ["霓虹", "宇宙", "自動射擊", "BOSS戰"],
    platform: "Web",
    shortPitch: "戰機自動開火，撐到 BOSS 降臨前先把火力堆起來。",
    description: "一款霓虹風格的星際射擊遊戲，玩家操控戰機閃避敵人、收集水晶、開啟 AI 託管與整備商店，在逐步升級的彈幕中挑戰 BOSS。",
    playUrl: "./games/neon-star-assault/index.html",
    theme: "magenta",
    featured: false,
    createdAt: "2026-06-05",
  },
  {
    id: "G12",
    title: "Chiayi Tycoon：永續大作戰",
    cover: "./assets/games/sdg-fps/cover-16x9.jpg",
    boxCover: "./assets/games/sdg-fps/cover-2x3.jpg",
    genre: ["模擬經營", "教育學習"],
    tags: ["SDG", "第一人稱", "嘉義在地", "Three.js", "經營決策"],
    platform: "Web",
    shortPitch: "用宣導槍感化奧客，邊賣阿里山冷泡茶邊救地球。",
    description: "第一人稱 3D 商店經營：採購嘉義在地食材（阿里山茶、東石蚵、民雄鳳梨）、上架定價、結帳補貨，剩食可選擇捐贈食物銀行或丟棄。隨機跳出 SDG 歷史考題，雇用員工自動化營運，奧客需用「永續宣導槍」感化五次才能結帳。內建 SDG 2 / 3 / 12 / 14 完整百科。",
    playUrl: "./games/901-05/index.html",
    theme: "violet",
    featured: false,
    createdAt: "2026-06-08",
  },
  {
    id: "G13",
    title: "ZONE X：極限孤島大逃殺",
    cover: "./assets/games/survival-arena/cover-16x9.jpg",
    boxCover: "./assets/games/survival-arena/cover-2x3.jpg",
    genre: ["射擊", "大逃殺"],
    tags: ["FPS", "Three.js", "AI 對手", "縮圈生存", "空投物資"],
    platform: "Web",
    shortPitch: "50 名 AI 玩家、縮圈毒霧、空投寶箱——你是最後一人嗎？",
    description: "純 Three.js 打造的 3D 大逃殺：800x800 隨機地形、50 個帶 AI 狀態機（巡邏/交戰/搜刮）的對手、毒圈定時縮小、隨機空投 M416/AWM/UMP45/S12K 武器。第一人稱射擊 + 載具系統 + 動態天氣，自閉執行不靠任何後端。",
    playUrl: "./games/survival-arena/index.html",
    theme: "ember",
    featured: false,
    createdAt: "2026-06-08",
  },
  {
    id: "G14",
    title: "NEON STAR：REBIRTH 30",
    cover: "./assets/games/neon-star-rebirth-30/cover-16x9.jpg",
    boxCover: "./assets/games/neon-star-rebirth-30/cover-2x3.jpg",
    genre: ["射擊", "卡牌"],
    tags: ["霓虹", "宇宙", "30階進化", "卡包商店"],
    platform: "Web",
    shortPitch: "卡包商店版 & 30 階進化，從核心脈衝開始重生。",
    description: "霓虹宇宙風卡牌射擊：30 階段進化系統、5 種武器模式（標準/螺旋/十字/波動/環爆）、Common/Rare/Legendary 三種卡包，用積分抽 EXP 或新彈幕。從核心脈衝一路進化到歐米茄終焉。",
    playUrl: "./games/neon-star-rebirth-30/index.html",
    theme: "magenta",
    featured: false,
    createdAt: "2026-06-09",
  },
  {
    id: "G15",
    title: "貪婪之星：乘數與炸彈",
    cover: "./assets/games/greedy-star/cover-16x9.jpg",
    genre: ["運氣", "策略"],
    tags: ["push your luck", "炸彈", "乘數", "見好就收"],
    platform: "Web",
    shortPitch: "一抽天堂、一抽地獄——你敢賭嗎？",
    description: "Push your luck 機制：按【要】抽下一顆，可能是 ×2/×3/×5 乘數、+10 鑽石、護盾，也可能是讓你歸零的黑色炸彈。按【不要】把本輪暫存分數存進銀行。三條命、首抽免炸彈，挑戰自己的最高紀錄。",
    playUrl: "./games/greedy-star/index.html",
    theme: "magenta",
    featured: false,
    createdAt: "2026-06-10",
  },
  {
    id: "K01",
    title: "瘋狂大賽車",
    cover: "./assets/games/kirin-racing/cover-16x9.jpg",
    boxCover: "./assets/games/kirin-racing/cover-2x3.jpg",
    genre: ["3D 賽車", "工程改裝", "體感控制"],
    tags: ["七軸改裝", "嘉義水城", "PS2 手把", "Pico W", "Three.js"],
    platform: "Web",
    shortPitch: "氣候改不了，能不能改載具？",
    description: "2026 嘉義街道淹過腳踝。你被水城工程聯盟徵召——七軸改裝決策（輪胎、軸距、驅動、動力、齒輪、車殼、底盤），跑兩圈嘉義八大地標賽道。沒人教你物理，你選的每個配件都會在賽道上見真章。⚠️ 大部分人在第二圈就翻車——你撐得過下一場暴雨嗎？",
    playUrl: "./games/kirin-racing/index.html",
    theme: "ember",
    featured: true,
    createdAt: "2026-06-06",
  },
];

const MOCK_VOTES = PROJECTS.flatMap((project, index) => {
  const count = 3 + ((index * 7) % 12);
  return Array.from({ length: count }, (_, voteIndex) => {
    const seed = index * 17 + voteIndex * 5;
    return {
      id: `mock_${project.id}_${voteIndex + 1}`,
      projectId: project.id,
      likedMost: ["節奏很明確", "美術風格有記憶點", "操作很快上手", "主題包裝完整", "關卡想法有趣"][seed % 5],
      suggestion: ["提示可以更清楚", "難度曲線可以再調整", "音效回饋可以更多", "結尾可以更完整", "新手教學可以再短一點"][(seed + 2) % 5],
      creativity: 3 + (seed % 3),
      art: 3 + ((seed + 1) % 3),
      gameplay: 3 + ((seed + 2) % 3),
      smoothness: 3 + ((seed + 3) % 3),
      completeness: 3 + ((seed + 4) % 3),
      createdAt: `2026-06-0${(voteIndex % 2) + 1}T${String(9 + voteIndex).padStart(2, "0")}:00:00Z`,
    };
  });
});
