const WORKS = [
  {
    code: "701-04",
    title: "REACT.X",
    genre: "反應挑戰",
    category: "動作與反應",
    hook: "0.3 秒的猶豫，就會讓你輸掉這一局。",
    tagline: "你的反應夠快嗎？節奏一加速，手眼協調會立刻被拆穿。",
    description: "一款適合現場挑戰的短局遊戲，越玩越想刷新自己的極限成績。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "REACT.X",
    coverTone: "tone-action",
    launchUrl: "./games/701-04/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1GtdA0gv97xpMtO9xmhHGYLMlz3SPjUHI"
  },
  {
    code: "701-016",
    title: "風味抉擇：漢堡帝國",
    genre: "經營挑戰",
    category: "經營策略",
    hook: "你以為只是賣漢堡？每個決定都在考驗你的老闆腦。",
    tagline: "價格、人氣、口碑和資金一起壓上來，你能把小店做成帝國嗎？",
    description: "在一連串經營選擇中累積資源，讓你的漢堡店從街角小攤一路升級。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "漢堡帝國",
    coverTone: "tone-strategy",
    launchUrl: "./games/701-016/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1vqtBQRozg91MpwgkZ4aj2WnN5Ol1aycL"
  },
  {
    code: "704-08",
    title: "八掌溪跑酷",
    genre: "第一人稱跑酷",
    category: "動作與反應",
    hook: "夕照很美，但你沒有時間欣賞。",
    tagline: "用第一人稱視角衝過八掌溪場景，下一秒的失誤就是撞擊。",
    description: "把在地風景包裝成速度挑戰，適合喜歡衝刺、閃避和臨場反應的玩家。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "跑酷",
    coverTone: "tone-action-parkour",
    launchUrl: "./games/704-08/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1CB5omA_LQUpTDBa3QPmLro0uYT099Fqa"
  },
  {
    code: "801-01",
    title: "嘉義美食大亨",
    genre: "模擬經營",
    category: "經營策略",
    hook: "從一盤小吃開始，吃下整座嘉義的市場。",
    tagline: "抽卡、升級、賺錢，把嘉義名店變成你的餐飲版圖。",
    description: "用收集與養成的節奏包裝在地美食題材，讓每一次升級都像開新店一樣有感。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "FOOD",
    coverTone: "tone-strategy-food",
    launchUrl: "./games/801-01/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1D6cMHIXr1_1ELYBne2qaw-WuC8VatObM"
  },
  {
    code: "804-02",
    title: "深海設施射擊戰",
    genre: "3D 射擊",
    category: "射擊與戰鬥",
    hook: "燈光照不到的地方，有東西正在靠近。",
    tagline: "在深海設施裡移動、瞄準、開火，撐過下一波才算活下來。",
    description: "點擊畫面進入沉浸模式，使用 WASD 與滑鼠操作，體驗黑暗場域裡的生存壓力。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "深海",
    coverTone: "tone-combat",
    launchUrl: "./games/804-02/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1CqeJvX-p3Fe1GMRS2Np2-4kJcfwVAqja"
  },
  {
    code: "804-11",
    title: "音效決鬥",
    genre: "動作音效",
    category: "射擊與戰鬥",
    hook: "請先打開聲音，這款遊戲靠氣勢決勝負。",
    tagline: "招式、音效與節奏一起壓上來，每次觸發都像在喊出必殺技。",
    description: "以聲音回饋包裝戰鬥體驗，適合現場試玩時用最短時間抓住注意力。",
    status: "package",
    statusLabel: "上架中",
    shelfLabel: "SOUND",
    coverLetters: "SFX",
    coverTone: "tone-combat-sound",
    launchUrl: "./games/804-11/index.html",
    folderUrl: "https://drive.google.com/drive/folders/19sTKhQ66AGtaZ522NtEBBO3cIAQtQsdf"
  },
  {
    code: "804-14",
    title: "八掌溪環保爭霸戰",
    genre: "環境策略",
    category: "永續環境",
    hook: "如果八掌溪需要一位守門人，你會怎麼出手？",
    tagline: "把環境知識變成對戰選擇，守住生態，也守住分數。",
    description: "透過策略判斷理解永續與保護行動，讓知識不只是答題，而是每一步取捨。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "八掌溪",
    coverTone: "tone-eco-river",
    launchUrl: "./games/804-14/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1jIVBoe3B1wJLXqrfuNmi0IXxfTByVMWt"
  },
  {
    code: "904-07",
    title: "深淵騎士",
    genre: "2D 動作平台",
    category: "動作與反應",
    hook: "往前走，深淵會告訴你哪一步太慢。",
    tagline: "操控騎士穿越關卡，靠節奏、跳躍和技能突破敵人封鎖。",
    description: "以動作平台玩法為核心，結合角色技能與關卡挑戰，適合想一路打到底的玩家。",
    status: "incomplete",
    statusLabel: "開發中",
    shelfLabel: "BETA",
    coverLetters: "深淵",
    coverTone: "tone-action-abyss",
    launchUrl: "./games/904-07/index.html",
    folderUrl: "https://drive.google.com/drive/folders/1EWG40UHFxxzzUZqsVdPTC1MdNVdqJYJP"
  },
  {
    code: "SDG",
    title: "永續島嶼建設者",
    genre: "建設模擬",
    category: "永續環境",
    hook: "你不是在蓋城市，你是在決定一座島的未來。",
    tagline: "發展、環境與社會福祉不會同時等你，選錯一步就會連鎖反應。",
    description: "打造島嶼、處理永續議題，在每個決策中看見城市治理的取捨。",
    status: "published",
    statusLabel: "上架中",
    shelfLabel: "PLAY",
    coverLetters: "SDG",
    coverTone: "tone-eco-city",
    launchUrl: "./games/sdg/index.html",
    folderUrl: "https://drive.google.com/drive/folders/11X-1QYl7Cscq6rnuwj7DeBpTor9UCUmP"
  }
];
